name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install
      
      - name: user email
        run:  git config --global user.email "prjwlsingh@gmai.com"
        
      - name: user name
        run:  git config --global user.name "prjwlsingh"

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          TOKEN1: ${{ secrets.TOKEN1 }}
